### ISSUE TITLE
Question: Connector to Token Signing

### ISSUE THREAD

**Issue by adrianbrink** [oraclize/dapp-proof-of-identity#1]
Hi,
awesome work.

Where in the codebase does it call out to the `Token Signing` chrome extension to select the correct certificate from the smart card. Generally I would appreciate it if you could point me to the point where the interaction with the smart card happens.

Thank you very much.

**Comment by D-Nice** [comment]
Thanks for your kind words Adrian.

The certificate is extracted at: https://github.com/oraclize/dapp-proof-of-identity/blob/5822a1d1b88e365205188806ea9eef88cd6b578c/ui/react-wallet-ui/src/components/MyWallet.js#L224-L225

The message signing occurs here: https://github.com/oraclize/dapp-proof-of-identity/blob/5822a1d1b88e365205188806ea9eef88cd6b578c/ui/react-wallet-ui/src/components/MyWallet.js#L484

You can get more info on the various API calls here https://github.com/hwcrypto/hwcrypto.js/wiki/APIv2
